version: '3.9'
services:
  i2b2:
    image: ${I2B2_DOCKER_IMAGE:?}
    build:
      context: ../build/package/i2b2
    ports:
      - "8081:8080"
    environment:
      - I2B2_DB_HOST=postgresql
      - I2B2_DB_PORT=5432
      - I2B2_DB_USER=postgres
      - I2B2_DB_PW=postgres
      - I2B2_DB_NAME=i2b2
      - WILDFLY_ADMIN_PASSWORD=admin
      - I2B2_DOMAIN_NAME=i2b2demo
      - I2B2_SERVICE_PASSWORD=changeme
      - DEFAULT_USER_PASSWORD=changeme
      - AXIS2_LOGLEVEL=DEBUG
    networks:
      intra-node:

  postgresql:
    image: postgres:14.2
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      intra-node:

  pgadmin:
    image: ghcr.io/tuneinsight/pgadmin-geco:${DATASOURCE_VERSION:?}
    build:
      context: ../build/package/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@tuneinsight.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=50
    ports:
      - "8033:80"
    networks:
      intra-node:

networks:
  intra-node:
    driver: bridge
