name: Run Gosec Security Scanner
on:
  push:
  workflow_dispatch:
jobs:
  ci-cd:
    name: Run Gosec Security Scanner
    runs-on: ubuntu-latest
    env:
      PUSH: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true
          cache-dependency-path: go.sum

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
